# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 06:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_fields_to_users_applications'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocd_id', models.CharField(db_index=True, help_text='Open Civic Data identifier', max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(choices=[('fi', 'Finnish'), ('en', 'English'), ('sv', 'Swedish')], max_length=7)),
                ('contact_method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=30)),
                ('divisions_of_interest', models.ManyToManyField(to='users.AdministrativeDivision')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YSO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yso_id', models.CharField(db_index=True, max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='ysos_of_interest',
            field=models.ManyToManyField(to='users.YSO'),
        ),
    ]
