# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='profile',
            name='firebase_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
