# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_add_firebase_token_to_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('pushbullet', 'Pushbullet'), ('sms', 'SMS'), ('firebase', 'Firebase')], max_length=30),
        ),
    ]
